#file: noinspection SpellCheckingInspection
name: Automatic Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Create Release from Tag
    runs-on: ubuntu-latest
    steps:
      - name: Await CI Completion
        uses: "lewagon/wait-on-check-action@v1.3.1"
        with:
          ref: ${{ github.ref }}
          check-name: "Build and Upload Artifacts"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Download CI Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          workflow: build.yml
          workflow_conclusion: success
          if_no_artifact_found: fail
          skip_unpack: true
      - name: Create Draft Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: true
          files: |
            *.zip